version: "3.0"
services:
  sink:
    container_name: z33_server_python_1_2
    build: ./Server
    tty: true
    cap_add:
      - NET_ADMIN
  source:
    container_name: z33_client_python_1_2
    build: ./Client
    tty: true
    cap_add:
      - NET_ADMIN
networks:
  z33_network:
    name: z33_network
